;; D3D9 depth surface identities. Device state tail: +21752 bound depth,
;; +21756 automatic depth owner, +21760 auto format, +21764 auto enabled.
;; Surface48: vtable, external refs, device, marker05, binding refs,
;; width,height,format,discard,monotonic backend identity,reserved,reserved.
;; Depth/stencil formats here implement depth only; stencil operations reject.
;; Shared across guest-thread instances. No initializer resets this sequence;
;; exhaustion is permanent, including when allocation subsequently fails.
(global $D3D9_DEPTH_SERIAL i32 (region.addr $D3D9_DEPTH_SERIAL 0))
(global $D3D9_DEPTH_SERIAL_SIZE i32 (region.size $D3D9_DEPTH_SERIAL))
(func $d3d9_depth_next_serial (result i32)
  (local $old i32)
  (loop $retry
    (local.set $old (i32.atomic.load (global.get $D3D9_DEPTH_SERIAL)))
    (if (i32.eq (local.get $old) (i32.const -1)) (then (return (i32.const 0))))
    (br_if $retry (i32.ne (i32.atomic.rmw.cmpxchg (global.get $D3D9_DEPTH_SERIAL)
      (local.get $old) (i32.add (local.get $old) (i32.const 1))) (local.get $old))))
  (i32.add (local.get $old) (i32.const 1)))
(func $d3d9_default_output (param $device i32) (param $depth i32)
  (call $d3dim_set_render_state (local.get $device) (i32.const 174) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 137) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 139) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 141) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 142) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 143) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 145) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 146) (i32.const 2))
  (call $d3dim_set_render_state (local.get $device) (i32.const 147) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 148) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 7) (local.get $depth))
  (call $d3dim_set_render_state (local.get $device) (i32.const 8) (i32.const 3))
  (call $d3dim_set_render_state (local.get $device) (i32.const 16) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 154) (i32.const 0x3f800000))
  (call $d3dim_set_render_state (local.get $device) (i32.const 155) (i32.const 0x3f800000))
  (call $d3dim_set_render_state (local.get $device) (i32.const 156) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 157) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 158) (i32.const 0x3f800000))
  (call $d3dim_set_render_state (local.get $device) (i32.const 159) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 160) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 166) (i32.const 0x3f800000))
  (call $d3dim_set_render_state (local.get $device) (i32.const 19) (i32.const 2))
  (call $d3dim_set_render_state (local.get $device) (i32.const 20) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 22) (i32.const 3))
  (call $d3dim_set_render_state (local.get $device) (i32.const 25) (i32.const 8))
  (call $d3dim_set_render_state (local.get $device) (i32.const 52) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 53) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 54) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 55) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 56) (i32.const 8))
  (call $d3dim_set_render_state (local.get $device) (i32.const 57) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 58) (i32.const -1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 59) (i32.const -1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 185) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 186) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 187) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 188) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 189) (i32.const 8))
  (call $d3dim_set_render_state (local.get $device) (i32.const 168) (i32.const 15))
  (call $d3dim_set_render_state (local.get $device) (i32.const 171) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 193) (i32.const -1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 206) (i32.const 0))
  (call $d3dim_set_render_state (local.get $device) (i32.const 207) (i32.const 2))
  (call $d3dim_set_render_state (local.get $device) (i32.const 208) (i32.const 1))
  (call $d3dim_set_render_state (local.get $device) (i32.const 209) (i32.const 1)))
;; Count externally owned default-pool resources/state blocks/depth surfaces.
;; Internal bindings do not prevent Reset; externally retained objects do.
(func $d3d9_reset_resource (param $wa i32) (param $delta i32)
  (local $kind i32) (local $tracked i32) (local $state i32)
  (local.set $kind (i32.load offset=12 (local.get $wa)))
  (local.set $tracked (i32.or (i32.eq (local.get $kind) (i32.const 0xd3d90003))
    (i32.eq (local.get $kind) (i32.const 0xd3d90005))))
  (if (i32.eq (local.get $kind) (i32.const 0xd3d90006))
    (then (local.set $tracked (i32.eqz (i32.load offset=60 (local.get $wa))))))
  (if (i32.or (i32.eq (local.get $kind) (i32.const 6)) (i32.eq (local.get $kind) (i32.const 7)))
    (then (local.set $tracked (i32.eqz (i32.load offset=36 (local.get $wa))))))
  (if (i32.or (i32.eq (local.get $kind) (i32.const 3)) (i32.eq (local.get $kind) (i32.const 5)))
    (then (local.set $tracked (i32.eqz (i32.load offset=44 (local.get $wa))))))
  (if (i32.eqz (local.get $tracked)) (then (return)))
  (local.set $state (call $g2w (call $d3d9_program_state (i32.load offset=8 (local.get $wa)))))
  (i32.store offset=21772 (local.get $state) (i32.add (i32.load offset=21772 (local.get $state)) (local.get $delta))))
(func $d3d9_depth_format (param $format i32) (result i32)
  (i32.or (i32.eq (local.get $format) (i32.const 80))
    (i32.or (i32.eq (local.get $format) (i32.const 75)) (i32.eq (local.get $format) (i32.const 77)))))
(func $d3d9_is_depth_surface (param $surface i32) (result i32)
  (if (i32.eqz (local.get $surface)) (then (return (i32.const 0))))
  (i32.eq (call $gl32 (i32.add (local.get $surface) (i32.const 12))) (i32.const 0xd3d90005)))
(func $d3d9_depth_addref (param $surface i32) (result i32)
  (local $wa i32) (local $entry i32) (local $refs i32)
  (local.set $wa (call $g2w (local.get $surface)))
  (local.set $refs (i32.load offset=4 (local.get $wa)))
  (if (i32.eqz (local.get $refs)) (then
    (call $d3d9_reset_resource (local.get $wa) (i32.const 1))
    (local.set $entry (call $dx_from_this (i32.load offset=8 (local.get $wa))))
    (store.field DxObject refcount (local.get $entry) (i32.add (load.field DxObject refcount (local.get $entry)) (i32.const 1)))))
  (local.set $refs (i32.add (local.get $refs) (i32.const 1)))
  (i32.store offset=4 (local.get $wa) (local.get $refs)) (local.get $refs))
(func $d3d9_depth_retire (param $surface i32) (result i32)
  (local $wa i32)
  (local.set $wa (call $g2w (local.get $surface)))
  (if (i32.load offset=44 (local.get $wa)) (then (return (i32.const 1))))
  (if (i32.ne (call $host_gpu_gl_call
    (select (i32.const 0x3000f) (i32.const 0x30008) (call $d3d9_is_color_surface (local.get $surface)))
    (local.get $wa) (i32.load offset=8 (local.get $wa))) (i32.const 1))
    (then (return (i32.const 0))))
  (i32.store offset=44 (local.get $wa) (i32.const 1)) (i32.const 1))
(func $d3d9_depth_collect (param $surface i32)
  (local $wa i32)
  (if (i32.eqz (local.get $surface)) (then (return)))
  (local.set $wa (call $g2w (local.get $surface)))
  (if (i32.or (i32.load offset=4 (local.get $wa)) (i32.load offset=16 (local.get $wa))) (then (return)))
  ;; Host copies identity before returning; the ordered queue owns its release.
  (if (i32.eqz (call $d3d9_depth_retire (local.get $surface))) (then (return)))
  (i32.store offset=12 (local.get $wa) (i32.const 0))
  (call $heap_free (local.get $surface)))
(func $d3d9_depth_unbind (param $surface i32)
  (local $wa i32)
  (if (i32.eqz (local.get $surface)) (then (return)))
  (local.set $wa (call $g2w (local.get $surface)))
  (i32.store offset=16 (local.get $wa) (i32.sub (i32.load offset=16 (local.get $wa)) (i32.const 1)))
  (call $d3d9_depth_collect (local.get $surface)))
(func $d3d9_depth_release (param $surface i32) (result i32)
  (local $wa i32) (local $refs i32) (local $device i32) (local $stack i32) (local $last i32)
  (local.set $wa (call $g2w (local.get $surface)))
  (local.set $refs (i32.load offset=4 (local.get $wa)))
  (if (i32.eqz (local.get $refs)) (then (return (i32.const 0))))
  (if (i32.and (i32.eq (local.get $refs) (i32.const 1)) (i32.eqz (i32.load offset=16 (local.get $wa)))) (then
    (if (i32.eqz (call $d3d9_depth_retire (local.get $surface))) (then (return (local.get $refs))))))
  (local.set $device (i32.load offset=8 (local.get $wa)))
  ;; Keep the last external child reference intact across a parked final
  ;; device release. On re-entry the same object drives the broker poll.
  (if (i32.and (i32.eq (local.get $refs) (i32.const 1))
    (i32.eq (load.field DxObject refcount (call $dx_from_this (local.get $device))) (i32.const 1))) (then
    (local.set $stack (global.get $esp))
    (call $handle_IDirect3DDevice9_Release (local.get $device) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))
    (if (global.get $d3d_render_token) (then (return (i32.const -1))))
    (global.set $esp (local.get $stack))
    (if (global.get $eax) (then (return (local.get $refs))))
    (local.set $last (i32.const 1))))
  (local.set $refs (i32.sub (local.get $refs) (i32.const 1)))
  (i32.store offset=4 (local.get $wa) (local.get $refs))
  (if (i32.eqz (local.get $refs)) (then
    (if (i32.eqz (local.get $last)) (then (call $d3d9_reset_resource (local.get $wa) (i32.const -1))))
    (call $d3d9_depth_collect (local.get $surface))
    (if (local.get $last) (then (return (i32.const 0))))
    (local.set $stack (global.get $esp))
    (call $handle_IDirect3DDevice9_Release (local.get $device) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))
    (global.set $esp (local.get $stack))))
  (local.get $refs))
(func $d3d9_depth_new (param $device i32) (param $width i32) (param $height i32)
  (param $format i32) (param $discard i32) (param $external i32) (result i32)
  (local $surface i32) (local $wa i32) (local $serial i32)
  (if (i32.or (local.get $device) (local.get $external)) (then
    (if (i32.eqz (call $d3d9_program_state (local.get $device))) (then (return (i32.const 0))))))
  (if (i32.or (i32.eqz (local.get $width)) (i32.or (i32.eqz (local.get $height))
    (i32.or (i32.gt_u (local.get $width) (i32.const 2048)) (i32.gt_u (local.get $height) (i32.const 2048))))) (then (return (i32.const 0))))
  (if (i32.eqz (call $d3d9_depth_format (local.get $format))) (then (return (i32.const 0))))
  (local.set $serial (call $d3d9_depth_next_serial))
  (if (i32.eqz (local.get $serial)) (then (return (i32.const 0))))
  (local.set $surface (call $heap_alloc (i32.const 48)))
  (if (i32.eqz (local.get $surface)) (then (return (i32.const 0))))
  (local.set $wa (call $g2w (local.get $surface))) (memory.fill (local.get $wa) (i32.const 0) (i32.const 48))
  (i32.store (local.get $wa) (global.get $DX_VTBL_D3DSURF9))
  (i32.store offset=8 (local.get $wa) (local.get $device))
  (i32.store offset=12 (local.get $wa) (i32.const 0xd3d90005))
  (i32.store offset=20 (local.get $wa) (local.get $width)) (i32.store offset=24 (local.get $wa) (local.get $height))
  (i32.store offset=28 (local.get $wa) (local.get $format)) (i32.store offset=32 (local.get $wa) (local.get $discard))
  (i32.store offset=36 (local.get $wa) (local.get $serial))
  (if (local.get $external) (then (drop (call $d3d9_depth_addref (local.get $surface)))))
  (local.get $surface))
(func $d3d9_depth_binding (param $device i32) (param $surface i32) (param $get i32)
  (local $state i32) (local $old i32) (local $wa i32) (local $rt i32)
  (global.set $eax (i32.const 0x8876086c))
  (local.set $state (call $d3d9_program_state (local.get $device)))
  (if (i32.eqz (local.get $state)) (then (return)))
  (local.set $old (call $gl32 (i32.add (local.get $state) (i32.const 21752))))
  (if (local.get $get) (then
    (if (i32.eqz (local.get $surface)) (then (return)))
    (call $gs32 (local.get $surface) (local.get $old))
    (if (i32.eqz (local.get $old)) (then (global.set $eax (i32.const 0x88760866)) (return)))
    (drop (call $d3d9_depth_addref (local.get $old)))
    (global.set $eax (i32.const 0)) (return)))
  (if (local.get $surface) (then
    (if (i32.eqz (call $d3d9_is_depth_surface (local.get $surface))) (then (return)))
    (local.set $wa (call $g2w (local.get $surface)))
    (if (i32.ne (i32.load offset=8 (local.get $wa)) (local.get $device)) (then (return)))
    (local.set $rt (call $d3ddev_rt_entry (local.get $device)))
    (if (i32.or (i32.lt_u (i32.load offset=20 (local.get $wa)) (call $d3d9_color_extent (local.get $device) (i32.const 0)))
      (i32.lt_u (i32.load offset=24 (local.get $wa)) (call $d3d9_color_extent (local.get $device) (i32.const 1)))) (then (return)))
  ))
  (if (i32.and (i32.ne (local.get $old) (i32.const 0)) (i32.ne (local.get $old) (local.get $surface))) (then
    (local.set $wa (call $g2w (local.get $old)))
    (if (i32.and (i32.eqz (i32.load offset=4 (local.get $wa))) (i32.eq (i32.load offset=16 (local.get $wa)) (i32.const 1))) (then
      (if (i32.eqz (call $d3d9_depth_retire (local.get $old))) (then (return)))))))
  (if (local.get $surface) (then
    (local.set $wa (call $g2w (local.get $surface)))
    (i32.store offset=16 (local.get $wa) (i32.add (i32.load offset=16 (local.get $wa)) (i32.const 1)))))
  (call $gs32 (i32.add (local.get $state) (i32.const 21752)) (local.get $surface))
  (call $d3d9_depth_unbind (local.get $old)) (global.set $eax (i32.const 0)))
