;; Independent D3D9 color surfaces. The first48 bytes intentionally share the
;; depth surface external/internal ownership protocol, but never its backend ID
;; namespace. Header80: +40 CPU pixels,+48 pitch,+52 bytes,+56 lock flags,
;; +60 pool,+64 usage,+68 dirty serial. Device+22020 holds the bound RT0;
;; zero means the implicit backbuffer (DxObject.misc0), not a NULL RT0.
(func $d3d9_is_color_surface (param $surface i32) (result i32)
  (if (i32.eqz (local.get $surface)) (then (return (i32.const 0))))
  (i32.eq (call $gl32 (i32.add (local.get $surface) (i32.const 12))) (i32.const 0xd3d90006)))

(func $d3d9_color_create (param $device i32) (param $width i32) (param $height i32)
  (param $format i32) (param $pool i32) (param $usage i32) (param $lockable i32) (param $out i32)
  (local $surface i32) (local $wa i32) (local $bytes i32) (local $serial i32)
  (global.set $eax (i32.const 0x8876086c))
  (if (i32.eqz (call $d3d9_state_bytes (local.get $out) (i32.const 4))) (then (return)))
  (call $gs32 (local.get $out) (i32.const 0))
  (if (i32.eqz (call $d3d9_program_state (local.get $device))) (then (return)))
  (if (i32.or (i32.eqz (local.get $width)) (i32.or (i32.eqz (local.get $height))
    (i32.or (i32.gt_u (local.get $width) (i32.const 2048)) (i32.gt_u (local.get $height) (i32.const 2048))))) (then (return)))
  (if (i32.eqz (i32.or (i32.eq (local.get $format) (i32.const 21))
    (i32.eq (local.get $format) (i32.const 22)))) (then (return)))
  (if (i32.or (i32.eq (local.get $pool) (i32.const 1)) (i32.gt_u (local.get $pool) (i32.const 3))) (then (return)))
  (local.set $bytes (i32.mul (i32.mul (local.get $width) (local.get $height)) (i32.const 4)))
  (global.set $eax (i32.const 0x8007000e))
  (local.set $serial (call $d3d9_depth_next_serial))
  (if (i32.eqz (local.get $serial)) (then (return)))
  (local.set $surface (call $heap_alloc (i32.add (i32.const 80) (local.get $bytes))))
  (if (i32.eqz (local.get $surface)) (then (return)))
  (local.set $wa (call $g2w (local.get $surface)))
  (memory.fill (local.get $wa) (i32.const 0) (i32.add (i32.const 80) (local.get $bytes)))
  (i32.store (local.get $wa) (global.get $DX_VTBL_D3DSURF9))
  (i32.store offset=8 (local.get $wa) (local.get $device))
  (i32.store offset=12 (local.get $wa) (i32.const 0xd3d90006))
  (i32.store offset=20 (local.get $wa) (local.get $width))
  (i32.store offset=24 (local.get $wa) (local.get $height))
  (i32.store offset=28 (local.get $wa) (local.get $format))
  (i32.store offset=32 (local.get $wa) (local.get $lockable))
  (i32.store offset=36 (local.get $wa) (local.get $serial))
  (i32.store offset=40 (local.get $wa) (i32.add (local.get $surface) (i32.const 80)))
  (i32.store offset=48 (local.get $wa) (i32.mul (local.get $width) (i32.const 4)))
  (i32.store offset=52 (local.get $wa) (local.get $bytes))
  (i32.store offset=60 (local.get $wa) (local.get $pool))
  (i32.store offset=64 (local.get $wa) (local.get $usage))
  (drop (call $d3d9_depth_addref (local.get $surface)))
  (call $gs32 (local.get $out) (local.get $surface))
  (global.set $eax (i32.const 0)))

;; Dimensions of bound RT0; presentation always retains the implicit slot.
(func $d3d9_color_extent (param $device i32) (param $height i32) (result i32)
  (local $state i32) (local $surface i32) (local $rt i32)
  (local.set $state (call $d3d9_program_state (local.get $device)))
  (if (i32.eqz (local.get $state)) (then (return (i32.const 0))))
  (local.set $surface (call $gl32 (i32.add (local.get $state) (i32.const 22020))))
  (if (local.get $surface) (then
    (return (call $gl32 (i32.add (local.get $surface) (select (i32.const 24) (i32.const 20) (local.get $height)))))))
  (local.set $rt (call $d3ddev_rt_entry (local.get $device)))
  (select (load.field DxObject height (local.get $rt)) (load.field DxObject width (local.get $rt)) (local.get $height)))

(func $d3d9_color_binding (param $device i32) (param $index i32) (param $surface i32)
  (local $state i32) (local $old i32) (local $wa i32) (local $rt i32)
  (global.set $eax (i32.const 0x8876086c))
  (if (i32.or (local.get $index) (i32.eqz (local.get $surface))) (then (return)))
  (local.set $state (call $d3d9_program_state (local.get $device)))
  (if (i32.eqz (local.get $state)) (then (return)))
  (local.set $state (call $g2w (local.get $state)))
  (local.set $old (i32.load offset=22020 (local.get $state)))
  (if (call $d3d9_is_color_surface (local.get $surface)) (then
    (local.set $wa (call $g2w (local.get $surface)))
    (if (i32.or (i32.ne (i32.load offset=8 (local.get $wa)) (local.get $device))
      (i32.or (i32.ne (i32.load offset=64 (local.get $wa)) (i32.const 1))
        (i32.ne (i32.load offset=56 (local.get $wa)) (i32.const 0)))) (then (return))))
  (else
    (local.set $rt (call $d3ddev_rt_entry (local.get $device)))
    (if (i32.ne (local.get $surface) (call $dx_get_wrapper_for_vtbl
      (call $dx_slot_of (local.get $rt)) (global.get $DX_VTBL_D3DSURF9))) (then (return)))
    (local.set $surface (i32.const 0))))
  (if (i32.and (i32.ne (local.get $old) (i32.const 0)) (i32.ne (local.get $old) (local.get $surface))) (then
    (local.set $wa (call $g2w (local.get $old)))
    (if (i32.and (i32.eqz (i32.load offset=4 (local.get $wa))) (i32.eq (i32.load offset=16 (local.get $wa)) (i32.const 1))) (then
      (if (i32.eqz (call $d3d9_depth_retire (local.get $old))) (then (return)))))))
  (if (local.get $surface) (then
    (local.set $wa (call $g2w (local.get $surface)))
    (i32.store offset=16 (local.get $wa) (i32.add (i32.load offset=16 (local.get $wa)) (i32.const 1)))))
  (i32.store offset=22020 (local.get $state) (local.get $surface))
  (call $d3d9_depth_unbind (local.get $old))
  (memory.fill (i32.add (local.get $state) (i32.const 21728)) (i32.const 0) (i32.const 24))
  (memory.fill (i32.add (local.get $state) (i32.const 22000)) (i32.const 0) (i32.const 20))
  (global.set $eax (i32.const 0)))

(func $d3d9_color_desc (param $surface i32) (param $out i32)
  (local $wa i32) (local $dest i32)
  (global.set $eax (i32.const 0x8876086c))
  (local.set $dest (call $d3d9_state_bytes (local.get $out) (i32.const 32)))
  (if (i32.eqz (local.get $dest)) (then (return)))
  (local.set $wa (call $g2w (local.get $surface)))
  (memory.fill (local.get $dest) (i32.const 0) (i32.const 32))
  (i32.store (local.get $dest) (i32.load offset=28 (local.get $wa)))
  (i32.store offset=4 (local.get $dest) (i32.const 1))
  (i32.store offset=8 (local.get $dest) (i32.load offset=64 (local.get $wa)))
  (i32.store offset=12 (local.get $dest) (i32.load offset=60 (local.get $wa)))
  (i32.store offset=24 (local.get $dest) (i32.load offset=20 (local.get $wa)))
  (i32.store offset=28 (local.get $dest) (i32.load offset=24 (local.get $wa)))
  (global.set $eax (i32.const 0)))

;; Return only after the ordered backend read/write has completed. The caller
;; retains its original stack and arguments while the normal render token parks.
(func $d3d9_color_sync (param $surface i32) (param $upload i32) (result i32)
  (local $result i32) (local $wa i32)
  (local.set $wa (call $g2w (local.get $surface)))
  (local.set $result (if (result i32) (global.get $d3d_render_token)
    (then (call $d3d_render_poll))
    (else (call $host_gpu_gl_call (select (i32.const 0x30011) (i32.const 0x30010) (local.get $upload))
      (local.get $wa) (i32.load offset=8 (local.get $wa))))))
  (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return (i32.const 0))))
  (i32.eq (local.get $result) (i32.const 1)))

(func $d3d9_color_lock (param $surface i32) (param $out i32) (param $rect i32) (param $flags i32)
  (local $wa i32) (local $dest i32) (local $rw i32) (local $left i32) (local $top i32)
  (global.set $eax (i32.const 0x8876086c))
  (local.set $wa (call $g2w (local.get $surface)))
  (local.set $dest (call $d3d9_state_bytes (local.get $out) (i32.const 8)))
  (if (i32.or (i32.eqz (local.get $dest)) (i32.or (i32.eqz (i32.load offset=32 (local.get $wa)))
    (i32.ne (i32.load offset=56 (local.get $wa)) (i32.const 0)))) (then (return)))
  ;; READONLY and NOSYSLOCK are implemented; never silently accept DISCARD,
  ;; NOOVERWRITE or a nonblocking request that would actually wait.
  (if (i32.and (local.get $flags) (i32.const 0xfffff7ef)) (then (return)))
  (if (local.get $rect) (then
    (local.set $rw (call $d3d9_state_bytes (local.get $rect) (i32.const 16)))
    (if (i32.eqz (local.get $rw)) (then (return)))
    (local.set $left (i32.load (local.get $rw))) (local.set $top (i32.load offset=4 (local.get $rw)))
    (if (i32.ge_u (local.get $left) (i32.load offset=8 (local.get $rw))) (then (return)))
    (if (i32.ge_u (local.get $top) (i32.load offset=12 (local.get $rw))) (then (return)))
    (if (i32.gt_u (i32.load offset=8 (local.get $rw)) (i32.load offset=20 (local.get $wa))) (then (return)))
    (if (i32.gt_u (i32.load offset=12 (local.get $rw)) (i32.load offset=24 (local.get $wa))) (then (return)))))
  (if (i32.eqz (call $d3d9_color_sync (local.get $surface) (i32.const 0))) (then (return)))
  (i32.store offset=56 (local.get $wa) (i32.or (local.get $flags) (i32.const 1)))
  (i32.store (local.get $dest) (i32.load offset=48 (local.get $wa)))
  (i32.store offset=4 (local.get $dest) (i32.add (i32.load offset=40 (local.get $wa))
    (i32.add (i32.mul (local.get $top) (i32.load offset=48 (local.get $wa))) (i32.mul (local.get $left) (i32.const 4)))))
  (global.set $eax (i32.const 0)))

(func $d3d9_color_unlock (param $surface i32)
  (local $wa i32)
  (global.set $eax (i32.const 0x8876086c))
  (local.set $wa (call $g2w (local.get $surface)))
  (if (i32.eqz (i32.load offset=56 (local.get $wa))) (then (return)))
  (if (i32.eqz (i32.and (i32.load offset=56 (local.get $wa)) (i32.const 16))) (then
    (if (i32.eqz (call $d3d9_color_sync (local.get $surface) (i32.const 1))) (then (return)))
    (i32.store offset=68 (local.get $wa) (i32.add (i32.load offset=68 (local.get $wa)) (i32.const 1)))))
  (i32.store offset=56 (local.get $wa) (i32.const 0)) (global.set $eax (i32.const 0)))

(func $d3d9_color_copy (param $device i32) (param $source i32) (param $dest i32)
  (local $src i32) (local $dst i32) (local $rt i32) (local $result i32)
  (global.set $eax (i32.const 0x8876086c))
  (if (i32.eqz (call $d3d9_program_state (local.get $device))) (then (return)))
  (if (i32.eqz (call $d3d9_is_color_surface (local.get $dest))) (then (return)))
  (local.set $dst (call $g2w (local.get $dest)))
  (if (i32.ne (i32.load offset=8 (local.get $dst)) (local.get $device)) (then (return)))
  (if (i32.ne (i32.load offset=60 (local.get $dst)) (i32.const 2)) (then (return)))
  (if (i32.load offset=56 (local.get $dst)) (then (return)))
  (if (i32.eqz (call $d3d9_is_color_surface (local.get $source))) (then
    (local.set $rt (call $d3ddev_rt_entry (local.get $device)))
    (if (i32.ne (local.get $source) (call $dx_get_wrapper_for_vtbl
      (call $dx_slot_of (local.get $rt)) (global.get $DX_VTBL_D3DSURF9))) (then (return)))
    (if (i32.ne (i32.load offset=28 (local.get $dst)) (i32.const 22)) (then (return)))
    (if (i32.ne (i32.load offset=20 (local.get $dst)) (load.field DxObject width (local.get $rt))) (then (return)))
    (if (i32.ne (i32.load offset=24 (local.get $dst)) (load.field DxObject height (local.get $rt))) (then (return)))
    (local.set $result (if (result i32) (global.get $d3d_render_token)
      (then (call $d3d_render_poll))
      (else (call $host_gpu_gl_call (i32.const 0x30012) (call $d3d9_gpu_descriptor (local.get $device)) (local.get $dst)))))
    (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return)))
    (if (i32.eq (local.get $result) (i32.const 1)) (then (global.set $eax (i32.const 0))))
    (return)))
  (local.set $src (call $g2w (local.get $source))) (local.set $dst (call $g2w (local.get $dest)))
  (if (i32.or (i32.ne (i32.load offset=8 (local.get $src)) (local.get $device))
    (i32.ne (i32.load offset=8 (local.get $dst)) (local.get $device))) (then (return)))
  (if (i32.or (i32.ne (i32.load offset=64 (local.get $src)) (i32.const 1))
    (i32.ne (i32.load offset=60 (local.get $dst)) (i32.const 2))) (then (return)))
  (if (i32.or (i32.load offset=56 (local.get $src)) (i32.load offset=56 (local.get $dst))) (then (return)))
  (if (i32.or (i32.ne (i32.load offset=20 (local.get $src)) (i32.load offset=20 (local.get $dst)))
    (i32.or (i32.ne (i32.load offset=24 (local.get $src)) (i32.load offset=24 (local.get $dst)))
      (i32.ne (i32.load offset=28 (local.get $src)) (i32.load offset=28 (local.get $dst))))) (then (return)))
  (if (i32.eqz (call $d3d9_color_sync (local.get $source) (i32.const 0))) (then (return)))
  (memory.copy (call $g2w (i32.load offset=40 (local.get $dst)))
    (call $g2w (i32.load offset=40 (local.get $src))) (i32.load offset=52 (local.get $src)))
  (i32.store offset=68 (local.get $dst) (i32.add (i32.load offset=68 (local.get $dst)) (i32.const 1)))
  (global.set $eax (i32.const 0)))
